// src/agents/ARVAgent.ts
import { BaseAgent } from "../NeuroEdge-Shared/core/BaseAgent";
import { EngineRegistry } from "../NeuroEdge-Shared/registry/EngineRegistry";

export class ARVAgent extends BaseAgent {
    constructor() {
        super({
            id: "ARVAgent",
            name: "ARV Agent",
            version: "1.0.0",
            description: "Agent responsible for ARV (Automated Result Verification) tasks, validating, checking, and verifying results generated by engines."
        });
    }

    async run(payload: any): Promise<any> {
        const reasoningEngine = EngineRegistry.get("ReasoningEngine");
        const dataEngine = EngineRegistry.get("DataEngine");

        if (!reasoningEngine || !dataEngine) {
            throw new Error("Required engines not registered: ReasoningEngine, DataEngine");
        }

        const processed = await dataEngine.process(payload);
        const verified = await reasoningEngine.reason({ data: processed });

        return {
            status: "verified",
            input: payload,
            processed,
            verified
        };
    }
}
